name: 'Ig post'
on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  ig-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: |
          git pull origin master

      - run: |
          npm install

      - name: Post to Instagram
        uses: ./instagram autoposter
        id: insta
        with:
          password: ${{ secrets.IG_PASSWORD }}